AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Parameters:
    EnvironmentParameter:
        Type: String
        Default: dev
        AllowedValues:
            - dev
            - stg
            - prod
        Description: Environment
Resources:
  KvScraperunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ../src/
      Handler: kv_scraper.lambda_handler
      Runtime: python3.8
      FunctionName: !Sub "${EnvironmentParameter}-kv-ee-scraper"
      Environment:
        Variables:
            EXTERNAL_LOG_LEVEL: INFO
            INTERNAL_LOG_LEVEL: DEBUG
            LOG_FORMAT: json
            ENVIRONMENT: !Ref EnvironmentParameter
      Policies:
        -
            Version: "2012-10-17"
            Statement:
                -   Effect: Allow
                    Action:
                        - "s3:GetObject"
                        - "s3:PutObject"
                        - "s3:ListBucket"
                        - "s3:GetObjectTagging"
                        - "s3:PutObjectTagging"
                        - "s3:PutObjectAcl"
                        - "s3:GetObjectAcl"
                    Resource: 
                        - !Join [ "", [ "arn:aws:s3:::", !Ref EnvironmentParameter, "-kinnisvara-etl-raw-data-daily-incremental" ] ]
                        - !Join [ "", [ "arn:aws:s3:::", !Ref EnvironmentParameter, "-kinnisvara-etl-raw-data-daily-incremental/*" ] ]
      Events:
        UpdateRakvere:
          Properties:
            Schedule: cron(17 04 * * ? *)
            Input: '{"city_name":"rakvere","deal_type":"all","room_nr":"all"}'
          Type: Schedule
        UpdateTartu11:
          Properties:
            Schedule: cron(10 11 * * ? *)
            Input: '{"city_name":"tartu","deal_type":1,"room_nr":1}'
          Type: Schedule
        UpdateTartu12:
          Properties:
            Schedule: cron(11 12 * * ? *)
            Input: '{"city_name":"tartu","deal_type":1,"room_nr":2}'
          Type: Schedule
        UpdateTartu13:
          Properties:
            Schedule: cron(12 13 * * ? *)
            Input: '{"city_name":"tartu","deal_type":1,"room_nr":3}'
          Type: Schedule
        UpdateTartu14:
          Properties:
            Schedule: cron(13 14 * * ? *)
            Input: '{"city_name":"tartu","deal_type":1,"room_nr":4}'
          Type: Schedule
        UpdateTartu15:
          Properties:
            Schedule: cron(14 15 * * ? *)
            Input: '{"city_name":"tartu","deal_type":1,"room_nr":5}'
          Type: Schedule
        UpdateTartu21:
          Properties:
            Schedule: cron(15 16 * * ? *)
            Input: '{"city_name":"tartu","deal_type":2,"room_nr":1}'
          Type: Schedule
        UpdateTartu22:
          Properties:
            Schedule: cron(15 17 * * ? *)
            Input: '{"city_name":"tartu","deal_type":2,"room_nr":2}'
          Type: Schedule
        UpdateTartu23:
          Properties:
            Schedule: cron(16 18 * * ? *)
            Input: '{"city_name":"tartu","deal_type":2,"room_nr":3}'
          Type: Schedule
        UpdateTartu24:
          Properties:
            Schedule: cron(17 19 * * ? *)
            Input: '{"city_name":"tartu","deal_type":2,"room_nr":4}'
          Type: Schedule
        UpdateTartu25:
          Properties:
            Schedule: cron(18 20 * * ? *)
            Input: '{"city_name":"tartu","deal_type":2,"room_nr":5}'
          Type: Schedule
        UpdateTallinn11:
          Properties:
            Schedule: cron(19 07 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":1,"room_nr":1}'
          Type: Schedule
        UpdateTallinn12:
          Properties:
            Schedule: cron(20 06 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":1,"room_nr":2}'
          Type: Schedule
        UpdateTallinn13:
          Properties:
            Schedule: cron(21 05 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":1,"room_nr":3}'
          Type: Schedule
        UpdateTallinn14:
          Properties:
            Schedule: cron(42 10 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":1,"room_nr":4}'
          Type: Schedule
        UpdateTallinn15:
          Properties:
            Schedule: cron(43 11 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":1,"room_nr":5}'
          Type: Schedule
        UpdateTallinn21:
          Properties:
            Schedule: cron(45 12 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":2,"room_nr":1}'
          Type: Schedule
        UpdateTallinn22:
          Properties:
            Schedule: cron(45 13 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":2,"room_nr":2}'
          Type: Schedule
        UpdateTallinn23:
          Properties:
            Schedule: cron(46 14 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":2,"room_nr":3}'
          Type: Schedule
        UpdateTallinn24:
          Properties:
            Schedule: cron(47 15 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":2,"room_nr":4}'
          Type: Schedule
        UpdateTallinn25:
          Properties:
            Schedule: cron(48 16 * * ? *)
            Input: '{"city_name":"tallinn","deal_type":2,"room_nr":5}'
          Type: Schedule
  ImportProcessedBucket:
    Type: AWS::S3::Bucket
    Properties: 
        BucketName: !Join [ "", [ !Ref EnvironmentParameter, "-kinnisvara-etl-raw-data-daily-incremental" ] ]
        AccessControl: "Private"

